############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Applications"
url = "applications/"
weight = 3

[[main]]
name = "News & Missions"
weight = 4
hasChildren = true

[[main]]
weight = 1
name = "News"
url = "news/"
parent = "News & Missions"

[[main]]
weight = 2
name = "Missions"
url = "missions/"
parent = "News & Missions"

[[main]]
weight = 5
name = "Generic"
url = "generic"


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "News"
url = "news/"
weight = 2

[[footer]]
name = "Missions"
url = "missions/"
weight = 3

[[footer]]
name = "Applications"
url = "applications/"
weight = 4

[[footer]]
name = "Generic"
url = "generic/"
weight = 5